### ISSUE TITLE
Using 4MB version of ESP32-WROVER

### ISSUE THREAD

**Issue by pebri86** [OtherCrashOverride/odroid-go-firmware#18]
Hi, 
I've ESP32 module with 4MB flash and 4MB psram lying around on my desk, and my plan is to use this for my copy of odroid-go.

Is it possible? if yes then how many apps could be fit on this module, and how can i achieve that? e.g change partition or what else.

best regard,
thanks.

**Comment by OtherCrashOverride** [comment]
Only the ODROID-GO hardware is supported.  The firmware currently uses the first 1MB of flash.  The number of applications is limited to 4,096 due to the FAT32 file system on the SD card.  The size of an application (.fw) determines whether it will fit in the internal flash.

There are currently no plans to support hardware other than ODROID-GO.

**Comment by pebri86** [comment]
Ah thanks for your explanation, i'll close the issue.
